version: '3.8'

services:

  api:
    image: socialmediaapi
    build:
      context: .
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SocialMediaDB;User ID=sa;Password=P@assword;TrustServerCertificate=true;Encrypt=false;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: P@assword
      ACCEPT_EULA: "Y"
    ports:
      - 14333:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@assword -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s   

networks:
  default:
    name: socialmedia-network

    